/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LWeRtwmF7p3
 */
import Link from "next/link"

export function SaaSdashboard() {
  return (
    <div className="flex flex-col h-screen">
      <header className="flex items-center justify-between px-6 py-4 bg-zinc-900 text-white">
        <div className="flex items-center space-x-4">
          <IconMountain className="h-6 w-6" />
          <span className="font-semibold text-xl">Acme AI</span>
        </div>
        <nav className="flex space-x-4">
          <Link className="text-white hover:text-zinc-500" href="#">
            Dashboard
          </Link>
          <Link className="text-white hover:text-zinc-500" href="#">
            Analytics
          </Link>
          <Link className="text-white hover:text-zinc-500" href="#">
            Reports
          </Link>
          <Link className="text-white hover:text-zinc-500" href="#">
            Settings
          </Link>
        </nav>
      </header>
      <div className="flex flex-1 overflow-hidden">
        <nav className="flex flex-col w-64 px-4 py-8 bg-zinc-900 text-white border-r">
          <h2 className="font-semibold text-xl mb-4">Modules</h2>
          <div className="space-y-2">
            <Link className="text-white hover:text-zinc-500" href="#">
              User Management
            </Link>
            <Link className="text-white hover:text-zinc-500" href="#">
              Data Visualization
            </Link>
            <Link className="text-white hover:text-zinc-500" href="#">
              AI Models
            </Link>
            <Link className="text-white hover:text-zinc-500" href="#">
              Performance Metrics
            </Link>
          </div>
        </nav>
        <main className="flex-1 p-6 overflow-auto">
          <section className="mb-6">
            <h2 className="font-semibold text-2xl mb-2">User Management</h2>
            <p className="mb-4">Manage and view all users within your system.</p>
            <img
              alt="User Management Chart"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/200",
                objectFit: "cover",
              }}
              width="500"
            />
          </section>
          <section className="mb-6">
            <h2 className="font-semibold text-2xl mb-2">Data Visualization</h2>
            <p className="mb-4">Visualize data from various sources in real-time.</p>
            <img
              alt="Data Visualization Chart"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/200",
                objectFit: "cover",
              }}
              width="500"
            />
          </section>
          <section className="mb-6">
            <h2 className="font-semibold text-2xl mb-2">AI Models</h2>
            <p className="mb-4">Monitor the performance of AI models.</p>
            <img
              alt="AI Models Chart"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/200",
                objectFit: "cover",
              }}
              width="500"
            />
          </section>
          <section className="mb-6">
            <h2 className="font-semibold text-2xl mb-2">Performance Metrics</h2>
            <p className="mb-4">Measure the performance of your system.</p>
            <img
              alt="Performance Metrics Chart"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/200",
                objectFit: "cover",
              }}
              width="500"
            />
          </section>
        </main>
      </div>
    </div>
  )
}


function IconMountain(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
